# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('enrollment_no', models.CharField(default=b'AXXXXXXXXXXX', max_length=12, primary_key=True, serialize=False, verbose_name=b'Enrollment No.')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=b'Gender', max_length=1)),
                ('dob', models.DateField(default=b'1994-01-01', verbose_name=b'Date of Birth')),
                ('contactno', models.IntegerField(verbose_name=b'Contact No.')),
                ('image', models.ImageField(upload_to=meet.models.upload_location, verbose_name=b'Add Image')),
                ('fblink', models.CharField(default=b'http://www.facebook.com/', max_length=100, verbose_name=b'Facebook ID Link')),
                ('linkedin', models.CharField(default=b'http://www.linkedin.com/', max_length=100, verbose_name=b'LinkedIn Link')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email ID')),
                ('branch', models.CharField(choices=[(b'BTCS', b'B.Tech Computer Science and Technology')], max_length=20)),
                ('batch', models.IntegerField(default=b'2016', verbose_name=b'Passout Year')),
                ('placed', models.CharField(max_length=100, verbose_name=b'Presently Placed at')),
            ],
            options={
                'ordering': ('name', 'batch'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name=b'Name')),
                ('cbatch', models.IntegerField(verbose_name=b'Passout Year')),
                ('cemail', models.EmailField(max_length=254, verbose_name=b'Email ID')),
                ('ccontact', models.IntegerField(verbose_name=b'Contact No.')),
                ('cdetail', models.TextField(max_length=500, verbose_name=b'Changes')),
            ],
            options={
                'ordering': ('cname', 'cemail'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, verbose_name=b'Name')),
                ('semail', models.EmailField(max_length=254, verbose_name=b'Email ID')),
                ('smessage', models.TextField(max_length=250, verbose_name=b'Message')),
            ],
            options={
                'ordering': ('semail', 'smessage'),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.Question'),
        ),
    ]
