# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='campus',
            field=models.CharField(choices=[(b'JP', b'Jaipur'), (b'MN', b'Manesar')], default=datetime.datetime(2016, 6, 6, 18, 54, 36, 682000, tzinfo=utc), max_length=20, verbose_name=b'Campus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='branch',
            field=models.CharField(choices=[(b'BTCS', b'B.Tech Computer Science and Technology')], max_length=20, verbose_name=b'Branch'),
        ),
    ]
