# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20160607_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='placed',
            field=models.CharField(default=b'Where are you presently working?', max_length=100, verbose_name=b'Presently Placed at'),
        ),
    ]
