# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20160607_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name=b'Things you will miss the most'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
